trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: dev-secrets

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az aks get-credentials -n gpitfutures-dev-aks -g gpitfutures-dev-rg-aks'
  name: kubectlContext
  displayName: Get Kubernetes Dev Context

- bash: |
    helm repo add stable https://kubernetes-charts.storage.googleapis.com/
  name: addRepo
  displayName: Add stable repo

- task: Bash@3
  inputs:
    filePath: 'launch-selenium-grid.sh'