trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    Contents: |
      grid-namespace.yml
      launch-selenium-grid.sh
      values.yaml
    TargetFolder: '$(build.artifactStagingDirectory)'
    OverWrite: true

- publish: $(build.artifactStagingDirectory)
  artifact: build-artifact 
